### ISSUE TITLE
Time references are stuck

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-sti/gitlab-docker#1]
![image](https://user-images.githubusercontent.com/176002/29541185-c472282c-86d2-11e7-9727-6793f15c479d.png)

The `updated a minute ago` kind of informations are not updating anymore.

Additionally, when logged in, time information are different in https://gitlab.epfl.ch/ and https://gitlab.epfl.ch/dashboard/projects even for the same project. Thought, this information looks correct in the top project page but individual files/folders data never show up:
![image](https://user-images.githubusercontent.com/176002/29541366-db71b816-86d3-11e7-926f-ef13d7a31eb1.png)

**Comment by domq** [comment]
Clearing the cache solves  (or masks?) the issue:

```
docker exec -it gitlabdocker_gitlabprod.1.iwwnhb6m17xipuic4qs6vtw8b gitlab-rake cache:clear
```

**Comment by ponsfrilus** [comment]
BTW the problem is still here. At some point the update date on the projects' list is not updated anymore.

**Comment by ponsfrilus** [comment]
Closing it now, as the recent updates seems to fix this issue.
