### ISSUE TITLE
Impossible to create a "Personal Access Tokens"

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-sti/gitlab-docker#2]
Steps to reproduce:
1. [Upper right > Your avatar > Settings > Access Token](https://gitlab.epfl.ch/profile/personal_access_tokens);
2. Create a new access token;
3. Reload the page: `Active Personal Access Tokens (0) - This user has no active Personal Access Tokens.`

Note that I have a "Status: Enabled" Two-Factor Authentication.

**Comment by domq** [comment]
Table `personal_access_tokens` was gefükt.

```
CREATE SEQUENCE personal_access_tokens_id_seq
    START WITH 2
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
UPDATE personal_access_tokens SET id=nextval('personal_access_tokens_id_seq') WHERE id IS NULL;
ALTER TABLE personal_access_tokens ALTER id SET NOT NULL;

ALTER TABLE ONLY personal_access_tokens
    ADD CONSTRAINT personal_access_tokens_pkey PRIMARY KEY (id);


ALTER TABLE personal_access_tokens ALTER id SET NOT NULL;
ALTER TABLE personal_access_tokens ALTER revoked SET NOT NULL;
ALTER TABLE personal_access_tokens ALTER revoked SET DEFAULT false;
UPDATE personal_access_tokens SET revoked = false WHERE revoked IS NULL;
```

![image](https://user-images.githubusercontent.com/1629585/29577894-7baf335a-876d-11e7-9911-34b6167ce26c.png)

#etvoilà !

**Comment by ponsfrilus** [comment]
Creating a new token result in a "Error 500" page

**Comment by ponsfrilus** [comment]
Confirmed after 10.0.5 update (2017-11-08)

**Comment by domq** [comment]
Gah. There was a piece missing from the unfüking kit:

```
ALTER TABLE ONLY personal_access_tokens ALTER COLUMN id SET DEFAULT nextval('personal_access_tokens_id_seq'::regclass);
```

Care to try again, and hopefully close this issue for good?

**Comment by ponsfrilus** [comment]
![image](https://user-images.githubusercontent.com/176002/33283173-512a0bb6-d3ab-11e7-8024-9d4f2164a87e.png)

Sound good !
