### ISSUE TITLE
gravatar URLs are not using https

### ISSUE THREAD

**Issue by sbancal** [epfl-sti/gitlab-docker#3]
We get the warning "Parts of this page are not secure"

Looking to it, it's gravatar.com image URLs.
e.g. http://www.gravatar.com/avatar/d3f662c7dae16e2195fb3530c8517458?s=72&d=identicon

**Comment by ponsfrilus** [comment]
Tips "nginx doesn't pass proxy headers by default" -> https://github.com/gitlabhq/gitlabhq/issues/690

**Comment by domq** [comment]
Closed with e23726c
