### ISSUE TITLE
Guest authentication (Tequila) leads to error

### ISSUE THREAD

**Issue by sbancal** [epfl-sti/gitlab-docker#5]
EPFL Guests accounts fall to the Tequila page "Tequila error : You don't have access to this document" when trying to authenticate.

![image](https://user-images.githubusercontent.com/895546/29670444-f298251a-88e6-11e7-98cb-3a6dcd16bd41.png)

**Comment by ponsfrilus** [comment]
Doesn't occur anymore, closing the issue.
